/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegulaminRouteImport } from './routes/regulamin'
import { Route as PolitykaPrywatnosciRouteImport } from './routes/polityka-prywatnosci'
import { Route as PaszportNajemcyRouteImport } from './routes/paszport-najemcy'
import { Route as KorzysciRouteImport } from './routes/korzysci'
import { Route as JakDzialamyRouteImport } from './routes/jak-dzialamy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NajemIndexRouteImport } from './routes/najem.index'
import { Route as NajemZapytaniaRouteImport } from './routes/najem.zapytania'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as AuthenticatedUstawieniaRouteImport } from './routes/_authenticated/ustawienia'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as NajemOfertyIndexRouteImport } from './routes/najem.oferty.index'
import { Route as NajemZapytaniaIdRouteImport } from './routes/najem.zapytania.$id'
import { Route as NajemOfertyIdRouteImport } from './routes/najem.oferty.$id'
import { Route as AuthenticatedNajemZainteresowaniRouteImport } from './routes/_authenticated/najem.zainteresowani'
import { Route as AuthenticatedNajemUmowyRouteImport } from './routes/_authenticated/najem.umowy'
import { Route as AuthenticatedNajemPaszportRouteImport } from './routes/_authenticated/najem.paszport'
import { Route as AuthenticatedNajemNoweZapytanieRouteImport } from './routes/_authenticated/najem.nowe-zapytanie'
import { Route as AuthenticatedNajemNowaOfertaRouteImport } from './routes/_authenticated/najem.nowa-oferta'
import { Route as AuthenticatedNajemMojeZapytaniaRouteImport } from './routes/_authenticated/najem.moje-zapytania'
import { Route as AuthenticatedNajemMojeOfertyRouteImport } from './routes/_authenticated/najem.moje-oferty'
import { Route as AuthenticatedNajemMojPaszportRouteImport } from './routes/_authenticated/najem.moj-paszport'
import { Route as AuthenticatedNajemConciergeRouteImport } from './routes/_authenticated/najem.concierge'
import { Route as AuthenticatedAdminPassportsRouteImport } from './routes/_authenticated/admin_.passports'
import { Route as AuthenticatedAdminPassportStatsRouteImport } from './routes/_authenticated/admin_.passport-stats'
import { Route as AuthenticatedNajemChatsIdRouteImport } from './routes/_authenticated/najem.chats.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulaminRoute = RegulaminRouteImport.update({
  id: '/regulamin',
  path: '/regulamin',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitykaPrywatnosciRoute = PolitykaPrywatnosciRouteImport.update({
  id: '/polityka-prywatnosci',
  path: '/polityka-prywatnosci',
  getParentRoute: () => rootRouteImport,
} as any)
const PaszportNajemcyRoute = PaszportNajemcyRouteImport.update({
  id: '/paszport-najemcy',
  path: '/paszport-najemcy',
  getParentRoute: () => rootRouteImport,
} as any)
const KorzysciRoute = KorzysciRouteImport.update({
  id: '/korzysci',
  path: '/korzysci',
  getParentRoute: () => rootRouteImport,
} as any)
const JakDzialamyRoute = JakDzialamyRouteImport.update({
  id: '/jak-dzialamy',
  path: '/jak-dzialamy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NajemIndexRoute = NajemIndexRouteImport.update({
  id: '/najem/',
  path: '/najem/',
  getParentRoute: () => rootRouteImport,
} as any)
const NajemZapytaniaRoute = NajemZapytaniaRouteImport.update({
  id: '/najem/zapytania',
  path: '/najem/zapytania',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin/setup',
  path: '/admin/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUstawieniaRoute = AuthenticatedUstawieniaRouteImport.update({
  id: '/ustawienia',
  path: '/ustawienia',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const NajemOfertyIndexRoute = NajemOfertyIndexRouteImport.update({
  id: '/najem/oferty/',
  path: '/najem/oferty/',
  getParentRoute: () => rootRouteImport,
} as any)
const NajemZapytaniaIdRoute = NajemZapytaniaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NajemZapytaniaRoute,
} as any)
const NajemOfertyIdRoute = NajemOfertyIdRouteImport.update({
  id: '/najem/oferty/$id',
  path: '/najem/oferty/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNajemZainteresowaniRoute =
  AuthenticatedNajemZainteresowaniRouteImport.update({
    id: '/najem/zainteresowani',
    path: '/najem/zainteresowani',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNajemUmowyRoute = AuthenticatedNajemUmowyRouteImport.update({
  id: '/najem/umowy',
  path: '/najem/umowy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNajemPaszportRoute =
  AuthenticatedNajemPaszportRouteImport.update({
    id: '/najem/paszport',
    path: '/najem/paszport',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNajemNoweZapytanieRoute =
  AuthenticatedNajemNoweZapytanieRouteImport.update({
    id: '/najem/nowe-zapytanie',
    path: '/najem/nowe-zapytanie',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNajemNowaOfertaRoute =
  AuthenticatedNajemNowaOfertaRouteImport.update({
    id: '/najem/nowa-oferta',
    path: '/najem/nowa-oferta',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNajemMojeZapytaniaRoute =
  AuthenticatedNajemMojeZapytaniaRouteImport.update({
    id: '/najem/moje-zapytania',
    path: '/najem/moje-zapytania',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNajemMojeOfertyRoute =
  AuthenticatedNajemMojeOfertyRouteImport.update({
    id: '/najem/moje-oferty',
    path: '/najem/moje-oferty',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNajemMojPaszportRoute =
  AuthenticatedNajemMojPaszportRouteImport.update({
    id: '/najem/moj-paszport',
    path: '/najem/moj-paszport',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNajemConciergeRoute =
  AuthenticatedNajemConciergeRouteImport.update({
    id: '/najem/concierge',
    path: '/najem/concierge',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPassportsRoute =
  AuthenticatedAdminPassportsRouteImport.update({
    id: '/admin_/passports',
    path: '/admin/passports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPassportStatsRoute =
  AuthenticatedAdminPassportStatsRouteImport.update({
    id: '/admin_/passport-stats',
    path: '/admin/passport-stats',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNajemChatsIdRoute =
  AuthenticatedNajemChatsIdRouteImport.update({
    id: '/najem/chats/$id',
    path: '/najem/chats/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/jak-dzialamy': typeof JakDzialamyRoute
  '/korzysci': typeof KorzysciRoute
  '/paszport-najemcy': typeof PaszportNajemcyRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/regulamin': typeof RegulaminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/ustawienia': typeof AuthenticatedUstawieniaRoute
  '/admin/setup': typeof AdminSetupRoute
  '/najem/zapytania': typeof NajemZapytaniaRouteWithChildren
  '/najem/': typeof NajemIndexRoute
  '/admin/passport-stats': typeof AuthenticatedAdminPassportStatsRoute
  '/admin/passports': typeof AuthenticatedAdminPassportsRoute
  '/najem/concierge': typeof AuthenticatedNajemConciergeRoute
  '/najem/moj-paszport': typeof AuthenticatedNajemMojPaszportRoute
  '/najem/moje-oferty': typeof AuthenticatedNajemMojeOfertyRoute
  '/najem/moje-zapytania': typeof AuthenticatedNajemMojeZapytaniaRoute
  '/najem/nowa-oferta': typeof AuthenticatedNajemNowaOfertaRoute
  '/najem/nowe-zapytanie': typeof AuthenticatedNajemNoweZapytanieRoute
  '/najem/paszport': typeof AuthenticatedNajemPaszportRoute
  '/najem/umowy': typeof AuthenticatedNajemUmowyRoute
  '/najem/zainteresowani': typeof AuthenticatedNajemZainteresowaniRoute
  '/najem/oferty/$id': typeof NajemOfertyIdRoute
  '/najem/zapytania/$id': typeof NajemZapytaniaIdRoute
  '/najem/oferty/': typeof NajemOfertyIndexRoute
  '/najem/chats/$id': typeof AuthenticatedNajemChatsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/jak-dzialamy': typeof JakDzialamyRoute
  '/korzysci': typeof KorzysciRoute
  '/paszport-najemcy': typeof PaszportNajemcyRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/regulamin': typeof RegulaminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/ustawienia': typeof AuthenticatedUstawieniaRoute
  '/admin/setup': typeof AdminSetupRoute
  '/najem/zapytania': typeof NajemZapytaniaRouteWithChildren
  '/najem': typeof NajemIndexRoute
  '/admin/passport-stats': typeof AuthenticatedAdminPassportStatsRoute
  '/admin/passports': typeof AuthenticatedAdminPassportsRoute
  '/najem/concierge': typeof AuthenticatedNajemConciergeRoute
  '/najem/moj-paszport': typeof AuthenticatedNajemMojPaszportRoute
  '/najem/moje-oferty': typeof AuthenticatedNajemMojeOfertyRoute
  '/najem/moje-zapytania': typeof AuthenticatedNajemMojeZapytaniaRoute
  '/najem/nowa-oferta': typeof AuthenticatedNajemNowaOfertaRoute
  '/najem/nowe-zapytanie': typeof AuthenticatedNajemNoweZapytanieRoute
  '/najem/paszport': typeof AuthenticatedNajemPaszportRoute
  '/najem/umowy': typeof AuthenticatedNajemUmowyRoute
  '/najem/zainteresowani': typeof AuthenticatedNajemZainteresowaniRoute
  '/najem/oferty/$id': typeof NajemOfertyIdRoute
  '/najem/zapytania/$id': typeof NajemZapytaniaIdRoute
  '/najem/oferty': typeof NajemOfertyIndexRoute
  '/najem/chats/$id': typeof AuthenticatedNajemChatsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/jak-dzialamy': typeof JakDzialamyRoute
  '/korzysci': typeof KorzysciRoute
  '/paszport-najemcy': typeof PaszportNajemcyRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/regulamin': typeof RegulaminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/ustawienia': typeof AuthenticatedUstawieniaRoute
  '/admin/setup': typeof AdminSetupRoute
  '/najem/zapytania': typeof NajemZapytaniaRouteWithChildren
  '/najem/': typeof NajemIndexRoute
  '/_authenticated/admin_/passport-stats': typeof AuthenticatedAdminPassportStatsRoute
  '/_authenticated/admin_/passports': typeof AuthenticatedAdminPassportsRoute
  '/_authenticated/najem/concierge': typeof AuthenticatedNajemConciergeRoute
  '/_authenticated/najem/moj-paszport': typeof AuthenticatedNajemMojPaszportRoute
  '/_authenticated/najem/moje-oferty': typeof AuthenticatedNajemMojeOfertyRoute
  '/_authenticated/najem/moje-zapytania': typeof AuthenticatedNajemMojeZapytaniaRoute
  '/_authenticated/najem/nowa-oferta': typeof AuthenticatedNajemNowaOfertaRoute
  '/_authenticated/najem/nowe-zapytanie': typeof AuthenticatedNajemNoweZapytanieRoute
  '/_authenticated/najem/paszport': typeof AuthenticatedNajemPaszportRoute
  '/_authenticated/najem/umowy': typeof AuthenticatedNajemUmowyRoute
  '/_authenticated/najem/zainteresowani': typeof AuthenticatedNajemZainteresowaniRoute
  '/najem/oferty/$id': typeof NajemOfertyIdRoute
  '/najem/zapytania/$id': typeof NajemZapytaniaIdRoute
  '/najem/oferty/': typeof NajemOfertyIndexRoute
  '/_authenticated/najem/chats/$id': typeof AuthenticatedNajemChatsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/jak-dzialamy'
    | '/korzysci'
    | '/paszport-najemcy'
    | '/polityka-prywatnosci'
    | '/regulamin'
    | '/reset-password'
    | '/admin'
    | '/messages'
    | '/ustawienia'
    | '/admin/setup'
    | '/najem/zapytania'
    | '/najem/'
    | '/admin/passport-stats'
    | '/admin/passports'
    | '/najem/concierge'
    | '/najem/moj-paszport'
    | '/najem/moje-oferty'
    | '/najem/moje-zapytania'
    | '/najem/nowa-oferta'
    | '/najem/nowe-zapytanie'
    | '/najem/paszport'
    | '/najem/umowy'
    | '/najem/zainteresowani'
    | '/najem/oferty/$id'
    | '/najem/zapytania/$id'
    | '/najem/oferty/'
    | '/najem/chats/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/jak-dzialamy'
    | '/korzysci'
    | '/paszport-najemcy'
    | '/polityka-prywatnosci'
    | '/regulamin'
    | '/reset-password'
    | '/admin'
    | '/messages'
    | '/ustawienia'
    | '/admin/setup'
    | '/najem/zapytania'
    | '/najem'
    | '/admin/passport-stats'
    | '/admin/passports'
    | '/najem/concierge'
    | '/najem/moj-paszport'
    | '/najem/moje-oferty'
    | '/najem/moje-zapytania'
    | '/najem/nowa-oferta'
    | '/najem/nowe-zapytanie'
    | '/najem/paszport'
    | '/najem/umowy'
    | '/najem/zainteresowani'
    | '/najem/oferty/$id'
    | '/najem/zapytania/$id'
    | '/najem/oferty'
    | '/najem/chats/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/jak-dzialamy'
    | '/korzysci'
    | '/paszport-najemcy'
    | '/polityka-prywatnosci'
    | '/regulamin'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/messages'
    | '/_authenticated/ustawienia'
    | '/admin/setup'
    | '/najem/zapytania'
    | '/najem/'
    | '/_authenticated/admin_/passport-stats'
    | '/_authenticated/admin_/passports'
    | '/_authenticated/najem/concierge'
    | '/_authenticated/najem/moj-paszport'
    | '/_authenticated/najem/moje-oferty'
    | '/_authenticated/najem/moje-zapytania'
    | '/_authenticated/najem/nowa-oferta'
    | '/_authenticated/najem/nowe-zapytanie'
    | '/_authenticated/najem/paszport'
    | '/_authenticated/najem/umowy'
    | '/_authenticated/najem/zainteresowani'
    | '/najem/oferty/$id'
    | '/najem/zapytania/$id'
    | '/najem/oferty/'
    | '/_authenticated/najem/chats/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  JakDzialamyRoute: typeof JakDzialamyRoute
  KorzysciRoute: typeof KorzysciRoute
  PaszportNajemcyRoute: typeof PaszportNajemcyRoute
  PolitykaPrywatnosciRoute: typeof PolitykaPrywatnosciRoute
  RegulaminRoute: typeof RegulaminRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminSetupRoute: typeof AdminSetupRoute
  NajemZapytaniaRoute: typeof NajemZapytaniaRouteWithChildren
  NajemIndexRoute: typeof NajemIndexRoute
  NajemOfertyIdRoute: typeof NajemOfertyIdRoute
  NajemOfertyIndexRoute: typeof NajemOfertyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamin': {
      id: '/regulamin'
      path: '/regulamin'
      fullPath: '/regulamin'
      preLoaderRoute: typeof RegulaminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polityka-prywatnosci': {
      id: '/polityka-prywatnosci'
      path: '/polityka-prywatnosci'
      fullPath: '/polityka-prywatnosci'
      preLoaderRoute: typeof PolitykaPrywatnosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paszport-najemcy': {
      id: '/paszport-najemcy'
      path: '/paszport-najemcy'
      fullPath: '/paszport-najemcy'
      preLoaderRoute: typeof PaszportNajemcyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/korzysci': {
      id: '/korzysci'
      path: '/korzysci'
      fullPath: '/korzysci'
      preLoaderRoute: typeof KorzysciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jak-dzialamy': {
      id: '/jak-dzialamy'
      path: '/jak-dzialamy'
      fullPath: '/jak-dzialamy'
      preLoaderRoute: typeof JakDzialamyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/najem/': {
      id: '/najem/'
      path: '/najem'
      fullPath: '/najem/'
      preLoaderRoute: typeof NajemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/najem/zapytania': {
      id: '/najem/zapytania'
      path: '/najem/zapytania'
      fullPath: '/najem/zapytania'
      preLoaderRoute: typeof NajemZapytaniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/admin/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ustawienia': {
      id: '/_authenticated/ustawienia'
      path: '/ustawienia'
      fullPath: '/ustawienia'
      preLoaderRoute: typeof AuthenticatedUstawieniaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/najem/oferty/': {
      id: '/najem/oferty/'
      path: '/najem/oferty'
      fullPath: '/najem/oferty/'
      preLoaderRoute: typeof NajemOfertyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/najem/zapytania/$id': {
      id: '/najem/zapytania/$id'
      path: '/$id'
      fullPath: '/najem/zapytania/$id'
      preLoaderRoute: typeof NajemZapytaniaIdRouteImport
      parentRoute: typeof NajemZapytaniaRoute
    }
    '/najem/oferty/$id': {
      id: '/najem/oferty/$id'
      path: '/najem/oferty/$id'
      fullPath: '/najem/oferty/$id'
      preLoaderRoute: typeof NajemOfertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/najem/zainteresowani': {
      id: '/_authenticated/najem/zainteresowani'
      path: '/najem/zainteresowani'
      fullPath: '/najem/zainteresowani'
      preLoaderRoute: typeof AuthenticatedNajemZainteresowaniRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/najem/umowy': {
      id: '/_authenticated/najem/umowy'
      path: '/najem/umowy'
      fullPath: '/najem/umowy'
      preLoaderRoute: typeof AuthenticatedNajemUmowyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/najem/paszport': {
      id: '/_authenticated/najem/paszport'
      path: '/najem/paszport'
      fullPath: '/najem/paszport'
      preLoaderRoute: typeof AuthenticatedNajemPaszportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/najem/nowe-zapytanie': {
      id: '/_authenticated/najem/nowe-zapytanie'
      path: '/najem/nowe-zapytanie'
      fullPath: '/najem/nowe-zapytanie'
      preLoaderRoute: typeof AuthenticatedNajemNoweZapytanieRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/najem/nowa-oferta': {
      id: '/_authenticated/najem/nowa-oferta'
      path: '/najem/nowa-oferta'
      fullPath: '/najem/nowa-oferta'
      preLoaderRoute: typeof AuthenticatedNajemNowaOfertaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/najem/moje-zapytania': {
      id: '/_authenticated/najem/moje-zapytania'
      path: '/najem/moje-zapytania'
      fullPath: '/najem/moje-zapytania'
      preLoaderRoute: typeof AuthenticatedNajemMojeZapytaniaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/najem/moje-oferty': {
      id: '/_authenticated/najem/moje-oferty'
      path: '/najem/moje-oferty'
      fullPath: '/najem/moje-oferty'
      preLoaderRoute: typeof AuthenticatedNajemMojeOfertyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/najem/moj-paszport': {
      id: '/_authenticated/najem/moj-paszport'
      path: '/najem/moj-paszport'
      fullPath: '/najem/moj-paszport'
      preLoaderRoute: typeof AuthenticatedNajemMojPaszportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/najem/concierge': {
      id: '/_authenticated/najem/concierge'
      path: '/najem/concierge'
      fullPath: '/najem/concierge'
      preLoaderRoute: typeof AuthenticatedNajemConciergeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/passports': {
      id: '/_authenticated/admin_/passports'
      path: '/admin/passports'
      fullPath: '/admin/passports'
      preLoaderRoute: typeof AuthenticatedAdminPassportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/passport-stats': {
      id: '/_authenticated/admin_/passport-stats'
      path: '/admin/passport-stats'
      fullPath: '/admin/passport-stats'
      preLoaderRoute: typeof AuthenticatedAdminPassportStatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/najem/chats/$id': {
      id: '/_authenticated/najem/chats/$id'
      path: '/najem/chats/$id'
      fullPath: '/najem/chats/$id'
      preLoaderRoute: typeof AuthenticatedNajemChatsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedUstawieniaRoute: typeof AuthenticatedUstawieniaRoute
  AuthenticatedAdminPassportStatsRoute: typeof AuthenticatedAdminPassportStatsRoute
  AuthenticatedAdminPassportsRoute: typeof AuthenticatedAdminPassportsRoute
  AuthenticatedNajemConciergeRoute: typeof AuthenticatedNajemConciergeRoute
  AuthenticatedNajemMojPaszportRoute: typeof AuthenticatedNajemMojPaszportRoute
  AuthenticatedNajemMojeOfertyRoute: typeof AuthenticatedNajemMojeOfertyRoute
  AuthenticatedNajemMojeZapytaniaRoute: typeof AuthenticatedNajemMojeZapytaniaRoute
  AuthenticatedNajemNowaOfertaRoute: typeof AuthenticatedNajemNowaOfertaRoute
  AuthenticatedNajemNoweZapytanieRoute: typeof AuthenticatedNajemNoweZapytanieRoute
  AuthenticatedNajemPaszportRoute: typeof AuthenticatedNajemPaszportRoute
  AuthenticatedNajemUmowyRoute: typeof AuthenticatedNajemUmowyRoute
  AuthenticatedNajemZainteresowaniRoute: typeof AuthenticatedNajemZainteresowaniRoute
  AuthenticatedNajemChatsIdRoute: typeof AuthenticatedNajemChatsIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedUstawieniaRoute: AuthenticatedUstawieniaRoute,
  AuthenticatedAdminPassportStatsRoute: AuthenticatedAdminPassportStatsRoute,
  AuthenticatedAdminPassportsRoute: AuthenticatedAdminPassportsRoute,
  AuthenticatedNajemConciergeRoute: AuthenticatedNajemConciergeRoute,
  AuthenticatedNajemMojPaszportRoute: AuthenticatedNajemMojPaszportRoute,
  AuthenticatedNajemMojeOfertyRoute: AuthenticatedNajemMojeOfertyRoute,
  AuthenticatedNajemMojeZapytaniaRoute: AuthenticatedNajemMojeZapytaniaRoute,
  AuthenticatedNajemNowaOfertaRoute: AuthenticatedNajemNowaOfertaRoute,
  AuthenticatedNajemNoweZapytanieRoute: AuthenticatedNajemNoweZapytanieRoute,
  AuthenticatedNajemPaszportRoute: AuthenticatedNajemPaszportRoute,
  AuthenticatedNajemUmowyRoute: AuthenticatedNajemUmowyRoute,
  AuthenticatedNajemZainteresowaniRoute: AuthenticatedNajemZainteresowaniRoute,
  AuthenticatedNajemChatsIdRoute: AuthenticatedNajemChatsIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface NajemZapytaniaRouteChildren {
  NajemZapytaniaIdRoute: typeof NajemZapytaniaIdRoute
}

const NajemZapytaniaRouteChildren: NajemZapytaniaRouteChildren = {
  NajemZapytaniaIdRoute: NajemZapytaniaIdRoute,
}

const NajemZapytaniaRouteWithChildren = NajemZapytaniaRoute._addFileChildren(
  NajemZapytaniaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  JakDzialamyRoute: JakDzialamyRoute,
  KorzysciRoute: KorzysciRoute,
  PaszportNajemcyRoute: PaszportNajemcyRoute,
  PolitykaPrywatnosciRoute: PolitykaPrywatnosciRoute,
  RegulaminRoute: RegulaminRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminSetupRoute: AdminSetupRoute,
  NajemZapytaniaRoute: NajemZapytaniaRouteWithChildren,
  NajemIndexRoute: NajemIndexRoute,
  NajemOfertyIdRoute: NajemOfertyIdRoute,
  NajemOfertyIndexRoute: NajemOfertyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
