ALTER TABLE public.rental_listings
  ADD COLUMN IF NOT EXISTS admin_fee NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS utilities_advance NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS utilities_by_usage BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allows_modifications BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allows_furniture_additions BOOLEAN NOT NULL DEFAULT false;